### PR TITLE
Closes #10 - Supporting of nested arrays

### LINKED ISSUE #10: Doesn't support arrays
Give this object:

```
{"nights":"7","dep_iata":"GLA","rooms":"1","room":[{"adults":"1","children":"0"}],"month":5,"year":2015}
```

The query string becomes:

```
?nights=7&dep_iata=GLA&rooms=1&room=%5Bobject%20Object%5D&month=5&year=2015
```

There needs to be support for arrays.

### PR DESCRIPTION
**Pull request by jbrooksuk**
All tests are passing :)

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ping @fernandofleury @lagden :)

**Comment by fernandofleury** [comment]
@jbrooksuk I'm really sorry for the late response! Thanks for your input on array conversion. I will work on it ASAP!

**Comment by jbrooksuk** [comment]
FWIW I'm using this in production :)

**Comment by lagden** [comment]
@jbrooksuk

I did another solution...

if you want to see:
code: https://gist.github.com/lagden/220e5882e09283720141
pen: http://codepen.io/lagden/pen/PqExPZ?editors=101

**Comment by jbrooksuk** [comment]
Ping.

**Comment by jbrooksuk** [comment]
Hello?

**Comment by jbrooksuk** [comment]
@lagden looking back at this code, I feel we should be storing an actual array. How about we merge your code into mine?

**Comment by lagden** [comment]
@jbrooksuk you can use https://www.npmjs.com/package/querystring
works very well...

I will create a small example for you.

**Comment by lagden** [comment]
@jbrooksuk take a look
https://github.com/lagden/querystring-usage

**Comment by fernandofleury** [comment]
I was refactoring the plugin to ES2015, but honestly during the middle of the process I kinda gave up cause I didn't see worth it. I was already covering this issue on it. Will have to fix it here now.

As @lagden if the querystring package serves your purpose, go for it.

As far as this PR goes, I think the code is a bit complex, and I will try to decouple a bit of it, to make it more concise as well. 

@jbrooksuk Can you provide an use case where the current state of the lib it doesn't work?

**Comment by jbrooksuk** [comment]
@fernandofleury ideally the array of data should return an array, otherwise you can't traverse through the query string (my changes, not yours).

**Pull request merged**
